import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
import { Grid } from "@mui/material";

// components

import Navbar from "@/components/Navbar";
import MemorieCard from "@/components/MemorieCard";
import Stories from "@/components/Stories";

export default function Home() {
  return (
    <>
      <Head>
        <title>Memories</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Stories/>
        <Grid container spacing={2} sx={{ mt: 2 }}>
          <Grid item>
            <MemorieCard />
          </Grid>
          <Grid item>
            <MemorieCard />
          </Grid>
          <Grid item>
            <MemorieCard />
          </Grid>
        </Grid>
      </main>
    </>
  );
}
